const db = require('./db');

const questions = {
  "Data Analytics": [
    { q: "What is the difference between mean, median, and mode?", a: "Mean is the arithmetic average of all values. Median is the middle value when data is sorted. Mode is the most frequently occurring value. Mean is sensitive to outliers, while median is more robust. For example, in [1,2,3,4,100], mean=22, median=3, mode=none." },
    { q: "Explain what a p-value means in hypothesis testing.", a: "A p-value is the probability of obtaining results at least as extreme as observed, assuming the null hypothesis is true. If p < 0.05, we reject the null hypothesis. A small p-value means strong evidence against H₀. It does NOT measure the probability that H₀ is true." },
    { q: "What is the difference between supervised and unsupervised learning?", a: "Supervised learning trains on labeled data (input→output pairs) — examples: regression, classification. Unsupervised learning finds patterns in unlabeled data — examples: clustering (K-Means), dimensionality reduction (PCA). Supervised needs ground truth labels; unsupervised discovers hidden structure." },
    { q: "How would you handle missing data in a dataset?", a: "Options: (1) Remove rows/columns if missingness < 5% and random. (2) Impute with mean/median/mode. (3) Use advanced imputation like KNN or MICE. (4) Flag missingness as a feature. (5) Use models that handle NaN natively (XGBoost). Choice depends on why data is missing (MCAR, MAR, MNAR)." },
    { q: "What is the difference between correlation and causation?", a: "Correlation means two variables move together statistically. Causation means one variable directly causes another. Correlation does NOT imply causation — a third confounding variable may explain both. Example: ice cream sales and drowning rates are correlated (both increase in summer), but ice cream doesn't cause drowning." },
    { q: "Explain the concept of overfitting in machine learning.", a: "Overfitting occurs when a model learns the training data too well, including noise, and fails to generalize to new data. Signs: high training accuracy, low test accuracy. Solutions: more data, regularization (L1/L2), dropout, cross-validation, pruning decision trees, early stopping." },
    { q: "What is a confusion matrix and what metrics can you derive from it?", a: "A confusion matrix shows TP, TN, FP, FN counts. Derived metrics: Accuracy = (TP+TN)/Total; Precision = TP/(TP+FP); Recall = TP/(TP+FN); F1 = 2×Precision×Recall/(Precision+Recall). Use F1 for imbalanced datasets, precision when false positives are costly, recall when false negatives are costly." },
    { q: "Describe the ETL process and its importance.", a: "ETL = Extract, Transform, Load. Extract: pull data from sources (databases, APIs, files). Transform: clean, normalize, aggregate, enrich. Load: write to target (data warehouse). ETL ensures data quality and consistency, making raw data analytics-ready. Modern variant: ELT (load first, transform in warehouse)." },
    { q: "What is the Central Limit Theorem?", a: "The CLT states that the sampling distribution of the sample mean approaches a normal distribution as sample size increases (n ≥ 30), regardless of the population's original distribution. This allows us to use normal distribution properties for hypothesis testing and confidence intervals." },
    { q: "How do you detect and handle outliers in a dataset?", a: "Detection: Z-score (>3 std devs), IQR method (Q1-1.5×IQR to Q3+1.5×IQR), box plots, scatter plots. Handling: Remove if data entry error; cap/floor (winsorization); transform with log/sqrt; use robust models (tree-based). Always investigate WHY outliers exist before removing." },
    { q: "What is the difference between OLAP and OLTP?", a: "OLTP (Online Transaction Processing): handles day-to-day transactions, row-oriented, highly normalized, fast writes, used in applications. OLAP (Online Analytical Processing): handles complex analytical queries, column-oriented, denormalized (star schema), optimized for aggregations, used in data warehouses." },
    { q: "Explain the concept of data normalization.", a: "Data normalization scales features to a standard range. Min-Max scaling: (x-min)/(max-min) → [0,1]. Z-score standardization: (x-mean)/std → mean=0, std=1. Important for KNN, SVM, neural networks. Tree-based models don't require normalization." },
    { q: "What is A/B testing and when would you use it?", a: "A/B testing is a controlled experiment comparing two versions (A=control, B=treatment) to determine which performs better on a metric. Requirements: random assignment, sufficient sample size, single variable change. Use statistical tests (t-test, chi-square) to determine significance." },
    { q: "What are the key differences between SQL and NoSQL databases?", a: "SQL: structured, tabular, ACID transactions, fixed schema, great for complex joins. NoSQL: flexible schema, horizontally scalable, types include document (MongoDB), key-value (Redis), wide-column (Cassandra), graph (Neo4j). Use SQL for structured/relational data; NoSQL for big data, real-time apps, unstructured data." },
    { q: "Explain the concept of feature engineering.", a: "Feature engineering transforms raw data into meaningful input features for ML models. Techniques: one-hot encoding, binning, polynomial features, date decomposition, log transformation, aggregations, lag features. Good features often matter more than model choice." },
    { q: "What is a decision tree and how does it work?", a: "A decision tree splits data recursively based on feature thresholds to maximize information gain (or minimize Gini impurity). At each node it finds the best split; leaf nodes contain predictions. Pros: interpretable, no scaling needed. Cons: prone to overfitting (solved by Random Forest)." },
    { q: "Describe the differences between Tableau, Power BI, and Python for data viz.", a: "Tableau: drag-and-drop, beautiful dashboards, best for business users, expensive. Power BI: Microsoft ecosystem, affordable, good for Excel users. Python (Matplotlib/Seaborn/Plotly): fully customizable, free, code-based, best for data scientists needing statistical or interactive custom visualizations." },
    { q: "What is dimensionality reduction and why is it useful?", a: "Dimensionality reduction reduces the number of features while preserving important information. Benefits: remove noise, reduce computation, avoid curse of dimensionality. Methods: PCA (linear, unsupervised), t-SNE (nonlinear, visualization), UMAP, autoencoders. PCA finds principal components that explain maximum variance." },
    { q: "How do you evaluate the performance of a regression model?", a: "Metrics: MAE (Mean Absolute Error) — interpretable, robust to outliers; MSE (Mean Squared Error) — penalizes large errors; RMSE — same units as target; R² — proportion of variance explained (1=perfect). Also use residual plots to check for patterns indicating model misspecification." },
    { q: "What is the difference between bagging and boosting?", a: "Bagging (Bootstrap Aggregating): trains multiple models in parallel on random data subsets, averages predictions — reduces variance. Example: Random Forest. Boosting: trains models sequentially, each correcting previous errors — reduces bias. Examples: XGBoost, LightGBM. Bagging reduces overfitting; boosting can overfit if not regularized." }
  ],
  "Web Development": [
    { q: "What is the difference between HTML, CSS, and JavaScript?", a: "HTML defines structure and content (the skeleton). CSS controls presentation and layout (the appearance). JavaScript adds interactivity and behavior (the logic). They follow separation of concerns: HTML for structure, CSS for style, JS for behavior." },
    { q: "Explain the DOM and how JavaScript interacts with it.", a: "The DOM (Document Object Model) is a tree-based in-memory representation of an HTML document. JavaScript interacts via: document.getElementById(), querySelector(), createElement(), appendChild(), addEventListener(). Changes to the DOM update the page dynamically without reload. React uses a Virtual DOM for performance." },
    { q: "What is the difference between GET and POST HTTP methods?", a: "GET: retrieves data, parameters in URL, idempotent, cacheable, limited data size — use for fetching. POST: sends data in request body, not cached, no size limit, not idempotent — use for creating/submitting. PUT updates entire resource, PATCH partially updates, DELETE removes." },
    { q: "What are RESTful APIs and how do they work?", a: "REST (Representational State Transfer) uses HTTP with stateless, client-server architecture. Resources identified by URLs. HTTP verbs: GET (read), POST (create), PUT/PATCH (update), DELETE. Responses in JSON. REST is lightweight and stateless vs SOAP which is heavy and uses XML." },
    { q: "Explain the concept of responsive design.", a: "Responsive design adapts websites to different screen sizes using: CSS media queries, flexible grid layouts (CSS Grid/Flexbox), fluid images (max-width:100%), viewport meta tag, relative units (%, em, rem, vw/vh). Mobile-first approach: design for small screens first, then add complexity for larger screens." },
    { q: "What is CSS Flexbox and how does it differ from CSS Grid?", a: "Flexbox is one-dimensional (row OR column) — ideal for components and aligning items in a line. Grid is two-dimensional (rows AND columns simultaneously) — ideal for page-level layouts. Use Flexbox for navigation bars, card rows; use Grid for full page layouts. They can be combined." },
    { q: "What is the difference between synchronous and asynchronous JavaScript?", a: "Synchronous: code executes line by line, blocking — next line waits for current to finish. Asynchronous: non-blocking (API calls, timers, file I/O) — other code runs while waiting. JavaScript uses the Event Loop to handle async via callbacks, Promises, and async/await." },
    { q: "Explain Promises and async/await in JavaScript.", a: "A Promise represents a future value with states: pending, fulfilled, rejected. Chained with .then()/.catch(). Async/await is syntactic sugar making async code look synchronous. 'async' declares an async function, 'await' pauses until Promise resolves. Use try/catch for error handling. Both prevent callback hell." },
    { q: "What is CORS and why is it important?", a: "CORS (Cross-Origin Resource Sharing) is a browser security mechanism restricting cross-origin requests. Servers allow them via headers: Access-Control-Allow-Origin. Prevents CSRF attacks. Configure in Express with the cors() middleware. Preflight OPTIONS request checks permissions before actual request." },
    { q: "What is the difference between localStorage and sessionStorage?", a: "localStorage: persists data with no expiry, survives browser close/reopen, ~5MB — use for user preferences, tokens. sessionStorage: data cleared when tab closes, ~5MB — use for temporary form data. Both are key-value stores. Neither is secure for sensitive data; use HttpOnly cookies instead." },
    { q: "Explain the concept of virtual DOM in React.", a: "React maintains a lightweight in-memory copy of the real DOM. When state changes, React re-renders the virtual DOM, diffs it with the previous version (reconciliation), and only updates actual DOM where changes occurred. This is faster than direct DOM manipulation as real DOM updates are expensive." },
    { q: "What is a closure in JavaScript?", a: "A closure is a function that retains access to its outer scope even after the outer function has returned. Used for: data privacy (module pattern), factory functions, currying, memoization. Example: function counter() { let count=0; return ()=>++count; } — the returned function remembers count." },
    { q: "What is the difference between == and === in JavaScript?", a: "== (loose equality) performs type coercion: '5'==5 is true. === (strict equality) checks both value AND type: '5'===5 is false. Always prefer === to avoid unexpected behavior. Special: null==undefined is true, null===undefined is false." },
    { q: "Explain event bubbling and event delegation.", a: "Event bubbling: events propagate up from target element through ancestors to root. Event delegation: attach one listener to a parent instead of many to children. Check event.target to identify the clicked element. Useful for dynamic content and better performance with many elements." },
    { q: "What are HTTP status codes and what do 200, 404, 500 mean?", a: "2xx success: 200 OK, 201 Created. 3xx redirect: 301 Moved Permanently. 4xx client errors: 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 429 Too Many Requests. 5xx server errors: 500 Internal Server Error, 502 Bad Gateway, 503 Service Unavailable." },
    { q: "What is the difference between authentication and authorization?", a: "Authentication: verifying WHO you are (identity) — login with password, OAuth, biometrics. Authorization: verifying WHAT you can access (permissions) — RBAC, scopes. Authentication happens first, then authorization. Example: logging into Gmail is authentication; whether you can access admin settings is authorization." },
    { q: "Explain the concept of Single Page Applications (SPAs).", a: "SPAs load a single HTML page and dynamically update content using JavaScript without full page reloads. Client-side routing (React Router). Benefits: fast navigation, app-like feel. Drawbacks: initial load slow, SEO challenges (solved by SSR/SSG), requires JavaScript." },
    { q: "What is webpack and why is it used?", a: "Webpack is a module bundler that combines JavaScript modules and dependencies into optimized files for browsers. Features: code splitting, tree shaking, loaders (process CSS, images, TypeScript), hot module replacement. Alternatives: Vite (faster, uses native ES modules), Parcel, Rollup." },
    { q: "What are the principles of SOLID in software development?", a: "S: Single Responsibility — class has one job. O: Open/Closed — open for extension, closed for modification. L: Liskov Substitution — subclasses replaceable for base class. I: Interface Segregation — specific interfaces over one general. D: Dependency Inversion — depend on abstractions. SOLID reduces coupling, improves maintainability." },
    { q: "What is the purpose of package.json in a Node.js project?", a: "package.json is the project manifest: records name, version, entry point, scripts (npm start/test/build), dependencies (runtime) and devDependencies (development only), engines (Node version). npm install reads it to install all dependencies. package-lock.json locks exact versions for reproducible installs." }
  ],
  "Backend Developer": [
    { q: "What is the difference between REST and GraphQL?", a: "REST: multiple endpoints, fixed data shape, can over/under-fetch, HTTP caching built-in. GraphQL: single endpoint, client specifies exact data needed (no over-fetching), strongly typed schema. Use REST for simple CRUD; GraphQL for complex interconnected data (social networks, dashboards)." },
    { q: "Explain the concept of middleware in Express.js.", a: "Middleware functions execute in the request-response cycle with access to req, res, next. Executed in order: app.use() registers them. Types: application-level, router-level, error-handling (4 params: err,req,res,next), third-party (cors, morgan, helmet). Uses: authentication, logging, body parsing, error handling." },
    { q: "What is database indexing and why is it important?", a: "An index (B-tree or hash) speeds up data retrieval by avoiding full table scans. Trade-offs: faster reads but slower writes (index must update), uses storage space. Index columns used in WHERE, JOIN, ORDER BY. Avoid over-indexing — too many indexes slow down writes significantly." },
    { q: "What are the ACID properties of a database transaction?", a: "Atomicity: all-or-nothing — if one step fails, all roll back. Consistency: transaction brings DB from valid state to valid state. Isolation: concurrent transactions don't interfere (isolation levels: read uncommitted→serializable). Durability: committed transactions persist even after system crash (WAL logs)." },
    { q: "Explain the difference between SQL JOINs.", a: "INNER JOIN: only matching rows from both tables. LEFT JOIN: all rows from left + matching from right (null if no match). RIGHT JOIN: all from right + matching from left. FULL OUTER JOIN: all rows from both. CROSS JOIN: cartesian product. SELF JOIN: table joined with itself." },
    { q: "What is caching and how does it improve performance?", a: "Caching stores frequently accessed data in fast memory to avoid expensive recomputation or DB queries. Types: in-memory (Redis, Memcached), CDN (static assets), HTTP cache (Cache-Control headers), memoization. Strategies: TTL (time-to-live), event-based invalidation, LRU eviction policy." },
    { q: "What is the difference between horizontal and vertical scaling?", a: "Vertical (scale-up): add more CPU/RAM to existing server — simpler but has limits and single point of failure. Horizontal (scale-out): add more servers — complex (requires load balancing, stateless design), handles more traffic, better fault tolerance. Cloud makes horizontal scaling easy (auto-scaling groups)." },
    { q: "Explain the concept of microservices architecture.", a: "Microservices breaks an app into small, independently deployable services each responsible for one business capability. Benefits: independent scaling, technology diversity, fault isolation. Challenges: distributed complexity, network latency, service discovery, data consistency. Communication via REST, gRPC, or message queues." },
    { q: "What is a message queue and when would you use one?", a: "A message queue (RabbitMQ, Kafka, SQS) enables asynchronous communication between services. Producer sends messages; consumer processes independently. Use for: decoupling services, traffic spike buffering, background jobs (emails), event streaming, guaranteed delivery. Kafka is best for high-throughput event streaming." },
    { q: "What is JWT and how does it work for authentication?", a: "JWT (JSON Web Token) has three base64-encoded parts: Header (algorithm), Payload (claims: user data, expiry), Signature (HMAC/RSA). Server creates token on login; client stores and sends in Authorization: Bearer header. Server verifies signature without DB lookup — stateless auth." },
    { q: "Explain the N+1 query problem and how to solve it.", a: "N+1 problem: fetching N records then making N additional queries for related data (1 for users + N for each user's posts). Solutions: eager loading (SQL JOINs or ORM include/preload), DataLoader (batching/caching for GraphQL), select_related in Django, include() in Eloquent." },
    { q: "What is connection pooling in databases?", a: "Connection pooling maintains reusable DB connections instead of creating/destroying per request (expensive). Pool manager provides available connections and returns them after use. Configure: min/max pool size, timeout, idle timeout. Libraries: pg-pool (Node), HikariCP (Java)." },
    { q: "Explain the concept of database normalization (1NF, 2NF, 3NF).", a: "1NF: atomic values, no repeating groups, unique rows. 2NF: meets 1NF + no partial dependencies (non-key cols depend on whole primary key). 3NF: meets 2NF + no transitive dependencies (non-key cols don't depend on other non-key cols). Denormalize for read performance in analytical systems." },
    { q: "What is an ORM and what are its advantages and disadvantages?", a: "ORM (Object-Relational Mapper) maps DB tables to code objects, abstracting SQL. Examples: Sequelize (Node), SQLAlchemy (Python), Hibernate (Java). Pros: less boilerplate, DB portability, prevents SQL injection. Cons: performance overhead, N+1 risk, hides complexity, steep learning curve for advanced queries." },
    { q: "What is Docker and why is it useful for backend development?", a: "Docker packages apps with all dependencies into portable containers. Key concepts: Dockerfile (build instructions), image (immutable snapshot), container (running instance), Docker Compose (multi-container apps). Benefits: eliminates environment inconsistencies, easy scaling, isolation, faster deployment." },
    { q: "Explain the concept of rate limiting in APIs.", a: "Rate limiting restricts API call frequency to prevent abuse and DoS attacks. Strategies: fixed window, sliding window, token bucket (refills over time), leaky bucket. Implement with Redis (track counts) or middleware (express-rate-limit). Return 429 Too Many Requests with Retry-After header." },
    { q: "What is the difference between process and thread?", a: "Process: independent program with own memory space, expensive to create, isolated. Thread: lightweight execution unit within a process, shares memory, faster creation, can cause race conditions. Node.js: single-threaded event loop + worker_threads for CPU-intensive tasks." },
    { q: "What is a deadlock in databases and how do you prevent it?", a: "Deadlock: two transactions each hold a lock the other needs, causing infinite wait. Prevention: consistent lock ordering, short transactions, timeout and retry, deadlock detection algorithms (wait-for graph). Databases auto-detect and resolve by aborting one transaction." },
    { q: "What are environment variables and why should you use them?", a: "Environment variables store configuration outside code (API keys, DB URLs, ports). Benefits: security (don't commit secrets to git), flexibility (different values per environment), 12-factor app compliance. In Node.js: use dotenv package. Never hardcode credentials in source code." },
    { q: "What is the difference between SQL and NoSQL databases?", a: "SQL (relational): structured tables, strict schema, ACID, powerful JOINs — PostgreSQL, MySQL. NoSQL: flexible schema, horizontally scalable, BASE consistency — document (MongoDB), key-value (Redis), column (Cassandra), graph (Neo4j). Choose based on data structure, consistency requirements, and scale needs." }
  ],
  "Cyber Security": [
    { q: "What is the difference between symmetric and asymmetric encryption?", a: "Symmetric: same key for encrypt/decrypt — fast, good for bulk data (AES-256). Key distribution is the challenge. Asymmetric: public key encrypts, private key decrypts (RSA, ECC) — slower, solves key distribution. TLS uses asymmetric to exchange symmetric key, then symmetric for actual data." },
    { q: "Explain the concept of a man-in-the-middle attack.", a: "MITM: attacker secretly intercepts/alters communication between two parties. Methods: ARP poisoning, DNS spoofing, SSL stripping, rogue WiFi hotspot. Prevention: HTTPS/TLS with certificate verification, HSTS, certificate pinning, VPN, multi-factor authentication." },
    { q: "What is SQL injection and how do you prevent it?", a: "SQL injection inserts malicious SQL into input fields. Example: username = ' OR '1'='1 bypasses login. Prevention: parameterized queries/prepared statements (most important), input validation, ORM, least privilege DB accounts, WAF. Never concatenate user input into SQL strings." },
    { q: "What is cross-site scripting (XSS) and how do you mitigate it?", a: "XSS injects malicious scripts into pages viewed by others. Types: stored (saved in DB), reflected (in URL), DOM-based. Impacts: cookie theft, session hijacking. Mitigation: output encoding/escaping, Content Security Policy (CSP) headers, HttpOnly cookies, input validation, DOMPurify." },
    { q: "Explain the CIA triad in information security.", a: "CIA Triad is the security foundation: Confidentiality — data accessible only to authorized parties (encryption, access control). Integrity — data accuracy, not tampered (hashing, digital signatures). Availability — systems accessible when needed (redundancy, DDoS protection, backups). All three must be balanced." },
    { q: "What is a firewall and how does it work?", a: "A firewall monitors and controls traffic based on security rules. Types: packet filtering (inspects headers), stateful (tracks connection state), application/proxy (inspects payload), NGFW (deep packet inspection). Allows/blocks based on: source IP, destination port, protocol, direction." },
    { q: "What is the difference between IDS and IPS?", a: "IDS (Intrusion Detection System): monitors and ALERTS on suspicious activity — passive, doesn't block. IPS (Intrusion Prevention System): monitors AND BLOCKS threats — active, inline in traffic. Both use signature-based and anomaly-based detection. SIEM aggregates alerts for correlation." },
    { q: "Explain the concept of zero-trust security.", a: "Zero Trust: 'never trust, always verify' — assume breach, verify every request regardless of network location. Principles: verify identity explicitly (MFA), least privilege access, micro-segmentation, continuous monitoring. Replaces VPN-based perimeter security. Implemented via identity providers and behavioral analytics." },
    { q: "What is phishing and how can organizations protect against it?", a: "Phishing: fraudulent messages tricking users into revealing credentials or installing malware. Types: spear phishing (targeted), whaling (executives), vishing (voice), smishing (SMS). Protection: email filtering (SPF/DKIM/DMARC), security awareness training, MFA, simulated phishing campaigns." },
    { q: "What is a VPN and how does it work?", a: "VPN creates an encrypted tunnel between client and server, hiding traffic from ISP and enabling access to private networks. Protocols: OpenVPN, WireGuard (fast, modern), IPSec. Uses: remote work, privacy, geo-restriction bypass. Split tunneling routes only some traffic through VPN." },
    { q: "Explain the concept of penetration testing.", a: "Pen testing simulates cyberattacks to find vulnerabilities. Phases: reconnaissance (info gathering), scanning (vulnerability assessment), exploitation (gain access), post-exploitation, reporting. Types: black-box (no knowledge), white-box (full access), grey-box. Tools: Metasploit, Burp Suite, Nmap." },
    { q: "What is two-factor authentication and why is it important?", a: "2FA requires two verification factors: something you know (password) + something you have (phone/token) or something you are (biometrics). Significantly reduces account compromise risk. TOTP (Google Authenticator) is more secure than SMS-based 2FA. Hardware keys (YubiKey) provide highest security." },
    { q: "What is a DDoS attack and how do you defend against it?", a: "DDoS: overwhelm server with traffic from many sources (botnet) to make service unavailable. Types: volumetric, protocol (SYN flood), application layer. Defense: CDN (Cloudflare), rate limiting, IP reputation filtering, anycast diffusion, traffic scrubbing, auto-scaling, WAF." },
    { q: "Explain the difference between hashing and encryption.", a: "Hashing: one-way function producing fixed-size digest — cannot be reversed. Used for passwords (bcrypt/Argon2), file integrity. Encryption: two-way — requires key to decrypt. Used for data in transit/rest. Never encrypt passwords — hash them with slow algorithms with salt (bcrypt, Argon2)." },
    { q: "What is HTTPS and how does SSL/TLS work?", a: "HTTPS = HTTP over TLS. TLS handshake: (1) Client hello. (2) Server sends certificate. (3) Client verifies with CA. (4) Key exchange (ECDHE). (5) Encrypted communication. Certificate proves server identity. TLS 1.3 is current standard — faster, more secure, removes weak cipher suites." },
    { q: "What is a buffer overflow attack?", a: "Buffer overflow: writing more data than buffer can hold, overwriting adjacent memory — can execute arbitrary code. C/C++ are vulnerable. Prevention: memory-safe languages (Rust, Go), bounds checking, stack canaries, ASLR (randomize memory layout), NX bit (no-execute), input validation." },
    { q: "What is social engineering in the context of security?", a: "Social engineering manipulates people into revealing information — exploits psychology over technical flaws. Examples: phishing, pretexting (fake identity), baiting (USB drops), quid pro quo, tailgating. Defense: security awareness training, verification procedures, healthy skepticism culture." },
    { q: "Explain the concept of least privilege principle.", a: "Least Privilege: users/processes have only minimum permissions needed. Benefits: limits blast radius if compromised, reduces insider threat, easier auditing. Apply to: user accounts (RBAC), service accounts, API keys, database access. Regularly audit and revoke unnecessary permissions." },
    { q: "What is OWASP and what are the top 10 security risks?", a: "OWASP provides free security resources. Top 10 (2021): 1.Broken Access Control 2.Cryptographic Failures 3.Injection 4.Insecure Design 5.Security Misconfiguration 6.Vulnerable Components 7.Authentication Failures 8.Software Integrity Failures 9.Logging Failures 10.SSRF. Essential web security reference." },
    { q: "What is a security audit and what does it involve?", a: "A security audit evaluates an organization's security posture against standards (ISO 27001, SOC 2, PCI-DSS). Involves: asset inventory, vulnerability scanning, penetration testing, policy review, access control review, log analysis. Output: risk-ranked findings and remediation recommendations." }
  ],
  "UI/UX Designer": [
    { q: "What is the difference between UI and UX design?", a: "UX (User Experience) focuses on overall feel and problem-solving — research, information architecture, user flows, wireframes, usability. UI (User Interface) focuses on visual presentation — colors, typography, components, icons. UX is the foundation; UI is the surface. A great UI with poor UX fails." },
    { q: "Explain the concept of user-centered design.", a: "User-centered design (UCD) places users at the center of every decision. Process: understand users (research, personas), define requirements, design solutions, prototype, test with users, iterate. Key principle: design FOR users, not for yourself. Involves users throughout, not just at the end." },
    { q: "What is a wireframe and how is it different from a prototype?", a: "Wireframe: low-fidelity static blueprint showing layout and content hierarchy — no colors or interaction. Created quickly in early stages. Prototype: interactive simulation — can be low (clickable wireframes) or high fidelity (realistic UI). Prototype tests user flows; wireframe communicates layout decisions." },
    { q: "What are the key principles of good UI design?", a: "Visual hierarchy (guide eye to important elements), consistency (similar elements behave similarly), feedback (system responds to actions), affordance (elements suggest their use), proximity (related items grouped), alignment (clean grids), white space (reduce cognitive load), contrast (readability)." },
    { q: "Explain the concept of information architecture.", a: "IA organizes content so users can find what they need. Includes: navigation systems, labeling, search functionality, site maps, categorization. Methods: card sorting (users group content), tree testing (test findability). Good IA reduces cognitive load and supports users' mental models." },
    { q: "What is A/B testing in the context of UX design?", a: "A/B testing compares two design variations with real users to see which performs better. Process: hypothesis → variants → split traffic → collect data → analyze statistically → implement winner. Test one variable at a time, ensure statistical significance, combine with qualitative insights." },
    { q: "How do you conduct user research?", a: "Qualitative (interviews, contextual inquiry, usability testing) — understand WHY. Quantitative (surveys, analytics, A/B testing) — understand WHAT/HOW MANY. Generative research (discover problems) vs evaluative (test solutions). Recruit representative users. Synthesize with affinity mapping." },
    { q: "What is a user persona and how do you create one?", a: "A persona is a data-driven representation of a user segment. Creation: conduct user research, identify patterns, segment by behavior/goals. Include: goals, frustrations, behaviors, technical proficiency. Use to align team on who you're designing for. Based on real research, not assumptions." },
    { q: "Explain the concept of accessibility in design.", a: "Accessibility ensures products are usable by people with disabilities. WCAG 2.1: Perceivable (alt text, captions), Operable (keyboard navigation), Understandable (clear language), Robust (works with assistive tech). AA compliance is legal requirement in many regions. Accessibility benefits all users (curb-cut effect)." },
    { q: "What is the difference between usability and accessibility?", a: "Usability: how easily ALL users achieve goals efficiently and with satisfaction — task success rate, time-on-task, error rate. Accessibility: ensuring people WITH DISABILITIES can use the product. Accessibility is a subset of usability. A product can be usable for most but inaccessible to users with disabilities." },
    { q: "What tools do you use for UI/UX design and why?", a: "Figma: industry standard, collaborative, component libraries, prototyping, design systems. Adobe XD: good prototyping, Adobe ecosystem. Sketch: Mac-only, mature plugins. Miro: collaborative whiteboarding. UsabilityHub/Maze: unmoderated testing. Hotjar: heatmaps, session recordings. Optimal Workshop: card sorting." },
    { q: "Explain the Gestalt principles in UI design.", a: "Gestalt principles describe visual pattern perception: Proximity (nearby = grouped), Similarity (similar = related), Continuity (eyes follow smooth paths), Closure (incomplete shapes perceived as complete), Figure/Ground (object vs background), Common fate (moving together = grouped). Essential for intuitive layouts." },
    { q: "What is a design system and why is it important?", a: "A design system is a collection of reusable components, guidelines, and standards. Includes: component library, typography scale, color palette, spacing, interaction patterns, accessibility guidelines, documentation. Benefits: consistency at scale, faster development, shared language between design and engineering." },
    { q: "How do you measure the success of a UX design?", a: "Metrics: Task success rate, Time-on-task, Error rate, System Usability Scale (SUS score), NPS, CSAT, Conversion rate, Bounce rate, Retention. Combine quantitative metrics with qualitative insights from user interviews and usability testing. Align metrics with business goals." },
    { q: "What is the difference between mobile-first and desktop-first design?", a: "Mobile-first: design for smallest screen first, progressively enhance — forces content prioritization, better performance, uses min-width media queries. Desktop-first: design for large screens, degrade for mobile — can lead to poor mobile experience. Mobile-first is the industry standard given mobile-majority web traffic." },
    { q: "Explain the concept of affordances in UX.", a: "Affordances are properties that suggest how to interact with objects. Perceived affordance: underlined blue text looks clickable; a button looks pressable. Good design makes affordances obvious. Anti-pattern: icon-only buttons without labels. Norman's concept: relationship between object properties and user capabilities." },
    { q: "What is card sorting and when do you use it?", a: "Card sorting is a research method where participants organize topics into groups, revealing mental models for IA. Types: open (participants create categories), closed (predefined categories). Use when designing/redesigning navigation. Analyze with similarity matrix. Recruit 15-20 participants for meaningful results." },
    { q: "What is the difference between qualitative and quantitative UX research?", a: "Qualitative: observational, explains WHY — interviews, usability tests, diary studies. Rich insights, small samples (5-8 users finds 80% of issues). Quantitative: numerical, explains WHAT — surveys, analytics, A/B tests. Large samples, statistically significant. Use both: quant identifies WHAT, qual explains WHY." },
    { q: "Explain the concept of user journey mapping.", a: "A user journey map visualizes experience over time — actions, thoughts, emotions, touchpoints, pain points, opportunities. Phases: awareness→consideration→use→loyalty. Based on real research. Reveals experience gaps, builds empathy, aligns teams. Different from user flow (focused on UI task completion)." },
    { q: "What is the Hick-Hyman Law and how does it apply to UI design?", a: "Hick's Law: decision time increases logarithmically with the number of choices. More options = slower decisions = higher cognitive load. Application: simplify navigation menus, progressive disclosure, clear single CTAs, onboarding wizards instead of complex forms. Fewer, focused choices lead to better UX." }
  ],
  "DevOps Engineer": [
    { q: "What is DevOps and what are its key principles?", a: "DevOps combines development and operations to shorten delivery cycles and improve reliability. Key principles: collaboration (break silos), automation (CI/CD, IaC), continuous improvement (feedback loops), shared responsibility, measurement (metrics). The Three Ways: flow (fast delivery), feedback (fast feedback), continual learning." },
    { q: "Explain the CI/CD pipeline and its stages.", a: "CI (Continuous Integration): developers merge frequently, automated builds and tests run on every commit. CD (Continuous Delivery): automates deployment to staging, manual approval to production. Continuous Deployment: auto-deploys to production. Pipeline: Source → Build → Test → Security Scan → Stage Deploy → Smoke Test → Prod Deploy." },
    { q: "What is Docker and how does containerization work?", a: "Docker packages apps with all dependencies into containers using OS-level virtualization (namespaces + cgroups). Containers share host kernel — lighter than VMs. Dockerfile defines layers (each instruction is a cached layer). Images are immutable; containers are running instances. Docker Compose orchestrates multi-container apps." },
    { q: "What is Kubernetes and when would you use it?", a: "Kubernetes (K8s) automates deployment, scaling, and management of containerized apps. Use when: managing many containers, need auto-scaling, self-healing, rolling updates, service discovery. Key objects: Pod (smallest unit), Deployment, Service, ConfigMap, Secret, Ingress, PersistentVolume." },
    { q: "Explain Infrastructure as Code (IaC) and its benefits.", a: "IaC manages infrastructure through code. Tools: Terraform (multi-cloud, declarative), CloudFormation, Ansible (configuration management). Benefits: version control infrastructure, reproducible environments, automated provisioning, reduced human error, documentation as code, easy disaster recovery." },
    { q: "What is the difference between blue-green and canary deployments?", a: "Blue-green: two identical environments (blue=live, green=new). Switch all traffic at once after testing — easy rollback, needs 2x infrastructure. Canary: gradually route small % to new version, increase if healthy — reduces blast radius. Feature flags enable canary per-user." },
    { q: "What are the key differences between Git rebase and merge?", a: "Merge: preserves history, creates merge commit, shows parallel development — non-destructive. Rebase: rewrites commit history, replays commits on another branch, creates linear history — cleaner log. Golden rule: never rebase public/shared branches. Rebase for cleaning feature branch; merge for integrating." },
    { q: "What is monitoring and observability in DevOps?", a: "Monitoring tracks predefined metrics. Observability is broader — understand internal state from external outputs. Three pillars: Metrics (Prometheus/Grafana), Logs (ELK/Loki — events, errors), Traces (Jaeger/Zipkin — distributed request paths). Alert on SLOs (Service Level Objectives)." },
    { q: "Explain the concept of auto-scaling.", a: "Auto-scaling adjusts compute resources based on demand. Types: horizontal (add/remove instances), vertical (resize). Triggers: CPU utilization, request rate, queue depth. AWS: Auto Scaling Groups. K8s: HPA (Horizontal Pod Autoscaler), VPA (vertical). Combine with predictive scaling for anticipated load." },
    { q: "What is Ansible and how does it differ from Terraform?", a: "Ansible: agentless configuration management, procedural YAML playbooks, manages software/config on existing servers, SSH-based — good for app deployment. Terraform: declarative IaC for provisioning infrastructure (VMs, networks), manages state, cloud-agnostic. Use together: Terraform provisions, Ansible configures." },
    { q: "What are the key components of a Kubernetes cluster?", a: "Control Plane: API Server (gateway), etcd (cluster state store), Scheduler (assigns pods to nodes), Controller Manager (ensures desired state). Worker Nodes: kubelet (node agent), kube-proxy (network rules), container runtime (containerd). Add-ons: CoreDNS, CNI plugins, metrics-server." },
    { q: "Explain the 12-Factor App methodology.", a: "12-Factor for cloud-native apps: 1.One codebase 2.Explicit dependencies 3.Config in env vars 4.Backing services as attached 5.Separate build/release/run 6.Stateless processes 7.Port binding 8.Scale via concurrency 9.Fast startup/shutdown 10.Dev/prod parity 11.Logs as streams 12.Admin processes." },
    { q: "What is a load balancer and when would you use one?", a: "Load balancer distributes traffic across multiple servers. Types: Layer 4 (TCP/UDP, faster), Layer 7 (HTTP, content-aware). Algorithms: round-robin, least connections, IP hash. Use for: high availability, scaling, SSL termination, health-check-based routing, zero-downtime deployments." },
    { q: "What is the difference between rolling update and recreate deployment strategies?", a: "Recreate: take down all old instances then deploy new — causes downtime, simple, use for dev. Rolling: gradually replace old with new — no downtime, allows rollback, brief mixed versions. Blue-green: no mixed versions, instant switch. Canary: test with subset first." },
    { q: "Explain the concept of service mesh.", a: "Service mesh handles service-to-service communication via sidecar proxies (Envoy) alongside each service. Features: mutual TLS, load balancing, circuit breaking, retries, distributed tracing, traffic management. Tools: Istio, Linkerd, Consul Connect. Adds complexity — use for complex microservice environments." },
    { q: "What are the key security considerations in a DevOps pipeline?", a: "DevSecOps: SAST (static analysis — SonarQube), DAST (dynamic testing — OWASP ZAP), dependency scanning (Snyk), container scanning (Trivy), secret detection (git-secrets, Vault), least privilege pipeline credentials, signed images, audit logs, immutable infrastructure." },
    { q: "What is log aggregation and why is it important?", a: "Log aggregation collects logs from distributed services into a centralized system for search and alerting. Essential for microservices across many hosts. Tools: ELK Stack (Elasticsearch, Logstash, Kibana), Grafana Loki, Splunk. Structured logging (JSON) enables better querying and parsing." },
    { q: "What is the difference between stateful and stateless applications?", a: "Stateless: each request is independent, no server-side session — horizontally scalable, easy to replace. Session data in JWT or shared cache (Redis). Stateful: server retains client state — harder to scale, needs sticky sessions. Kubernetes prefers stateless apps; stateful apps need PersistentVolumes." },
    { q: "Explain the concept of chaos engineering.", a: "Chaos engineering deliberately injects failures to discover weaknesses. Pioneered by Netflix (Chaos Monkey). Process: define steady-state → hypothesize it continues → inject failures (kill instances, latency, partitions) → observe → fix. Tools: Gremlin, LitmusChaos (K8s). Builds confidence in system resilience." },
    { q: "What is a reverse proxy and how does Nginx function as one?", a: "Reverse proxy sits in front of servers, forwarding client requests to backends. Nginx: receives requests, forwards to upstream servers (proxy_pass), returns responses. Benefits: load balancing, SSL termination, caching, compression, security (hides backend), rate limiting, static file serving." }
  ]
};

db.serialize(() => {

  db.run("DELETE FROM questions");

  const stmt = db.prepare(
    "INSERT INTO questions (field, question, correct_answer) VALUES (?, ?, ?)"
  );

  let count = 0;

  for (const [field, qs] of Object.entries(questions)) {

    for (const item of qs) {

      stmt.run(field, item.q, item.a);

      count++;
    }
  }

  stmt.finalize();

  db.get("SELECT COUNT(*) AS total FROM questions", (err, row) => {

    if (err) {
      console.log(err);
    } else {

      console.log(` Seeded ${count} questions`);
      console.log(` Total in DB: ${row.total}`);
    }

    process.exit(0);
  });

});